#pragma once

#include <memory>

#include "ID3D11FrameworkExtension.h"

/*
 * A framework for D3D11 rendering.
 * The D3D11 specific code was generated by ChatGPT.
 */
class D3D11Framework
{
public:
	// Create the D3D11 framework.
	D3D11Framework();
	
	// Destroy the D3D11 framework.
	~D3D11Framework();

	// Get some internal values from the D3D11 framework to initialize other graphics systems.
	D3D11Internals GetD3D11Internals() const;

	// Set an extension to add extra functionality to the Windows event loop.
	void SetExtension(std::unique_ptr<ID3D11FrameworkExtension> extension);
	
	// Run the Windows event loop.
	void EventLoop() const;

private:
	// Create the render target.
	void CreateRenderTarget();

	// Clean-up the render target.
	void CleanupRenderTarget();
	
	// Process Windows events.
	static LRESULT WINAPI WndProc(HWND hWnd, UINT msg, WPARAM wParam, LPARAM lParam);

	// D1D11 internal data.
	WNDCLASSEXW m_wc = { 0 };
	HWND m_hwnd = NULL;
	ID3D11Device* m_pd3dDevice = nullptr;
	ID3D11DeviceContext* m_pd3dDeviceContext = nullptr;
	IDXGISwapChain* m_pSwapChain = nullptr;
	ID3D11RenderTargetView* m_mainRenderTargetView = nullptr;

	// The extension which allows extra functionality to be run inside the Windows event loop.
	std::unique_ptr<ID3D11FrameworkExtension> m_extension;
};
