#pragma once

#include <memory>

#include "ID3D11FrameworkExtension.h"
#include "ISimulation.h"

/*
 * A user interface to show and control Conway's Game of Life.
 */
class UserInterface : public ID3D11FrameworkExtension
{
public:
	// Create the user interface.
	UserInterface(const D3D11Internals& internals);
	
	// Destroy the user interface.
	virtual ~UserInterface() override;

	// Set the interface which allows us to control and access the simulation.
	void SetSimulation(std::unique_ptr<ISimulation> simulation);

private:
	// Interface which allows us to control and access the simulation.
	std::unique_ptr<ISimulation> m_simulation;

	// ID3D11FrameworkExtension interface implementation.
	virtual void Render() const override;
	virtual void Present() const override;
	virtual bool ProcessEvent(HWND hWnd, UINT msg, WPARAM wParam, LPARAM lParam) const override;

	// Render the controls which allow us to load and save simulations.
	void RenderFileControls(bool isRunning) const;
	
	// Render the controls which allow us to control the running of the simulation.
	void RenderPlaybackControls(bool isRunning) const;
	
	// Render the controls.
	void RenderControls() const;
	
	// Render the grid which shows the state of the simulation and all the living cells.
	void RenderGrid() const;

	// Open a file dialog to choose a pathname to load a simulation from.
	// This Windows specific code was generated by ChatGPT.
	std::optional<std::filesystem::path> OpenFileDialog() const;
	
	// Open a file dialog to choose a pathname to save the simulation to.
	// This Windows specific code was generated by ChatGPT.
	std::optional<std::filesystem::path> SaveFileDialog() const;
};
